name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC (adjust as needed)
  workflow_dispatch:   # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Ensure you're checking out your default branch (e.g., master or main)
          ref: master

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/runelite/runelite.git || echo "Upstream already exists"

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout master
          git merge upstream/master --no-edit
        # If your default branch is 'main', adjust upstream/master to upstream/main accordingly.

      - name: Push Changes to Fork
        run: git push origin master
